# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!
targets = ['EasyFast', 'EasyFast_Dev', 'EasyFast_Test']

targets.each do |t|
  target t do
    # Comment the next line if you don't want to use dynamic frameworks
    pod 'ReactiveObjC'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'IQKeyboardManager'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'DateTools'
    pod 'YYKit'
    pod 'LYEmptyView'
    pod 'CYLTabBarController'
    pod 'QMUIKit/QMUIComponents/QMUIButton'
    pod 'QMUIKit/QMUIComponents/QMUITableView'
    pod 'QMUIKit/QMUIComponents/QMUILabel'
    pod 'QMUIKit/QMUIComponents/QMUITextField'
    pod 'QMUIKit/QMUIComponents/QMUITableViewCell'
    pod 'GKNavigationBar'
    pod 'JXCategoryView'
    pod 'SDCycleScrollView','>= 1.80'
    pod 'RollingNotice'
    pod 'YZTagList'
    pod 'WebViewJavascriptBridge', '~> 6.0'
    pod 'BGFMDB', '~> 2.0.9'
    pod 'SSZipArchive'
    pod "QPDialCodePickerView"
    pod 'JCore'
    pod 'JVerification'
    # Pods for EasyFast
  end

end
