# Uncomment the next line to define a global platform for your project
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
platform :ios, '9.0'
#use_frameworks!
use_modular_headers!
inhibit_all_warnings!
targets = ['EasyFast', 'EasyFast_Dev', 'EasyFast_Test']

targets.each do |t|
  target t do
    # Comment the next line if you don't want to use dynamic frameworks
    pod 'ReactiveObjC'
    pod 'AFNetworking'
    pod 'MJRefresh'
    pod 'Masonry'
    pod 'IQKeyboardManager'
    pod 'SDWebImage'
    pod 'MBProgressHUD'
    pod 'DateTools'
    pod 'YYKit'
    pod 'LYEmptyView'
    pod 'CYLTabBarController'
    pod 'QMUIKit/QMUIComponents/QMUIButton'
    pod 'QMUIKit/QMUIComponents/QMUITableView'
    pod 'QMUIKit/QMUIComponents/QMUILabel'
    pod 'QMUIKit/QMUIComponents/QMUITextField'
    pod 'QMUIKit/QMUIComponents/QMUITableViewCell'
    pod 'GKNavigationBar'
    pod 'JXCategoryView'
    pod 'SDCycleScrollView','>= 1.80'
    pod 'RollingNotice'
    pod 'YZTagList'
    pod 'WebViewJavascriptBridge', '~> 6.0'
    pod 'BGFMDB', '~> 2.0.9'
    pod 'SSZipArchive'
    pod "QPDialCodePickerView"
    pod 'JCore'
    pod 'JVerification'
    pod 'BRPickerView'
#    pod 'ISVImageScrollView', '~> 0.2.0'
    pod 'TXIMSDK_TUIKit_iOS'
    pod 'BaiduMapKit','~>2.10.2'
    pod 'ZLPhotoBrowser'
    pod 'JSBadgeView'
#    pod 'BMKLocationKit'


#  友盟
    pod 'UMCCommon'
    pod 'UMCShare/Social/WeChat'
    pod 'UMCShare/Social/ReducedQQ'
    pod 'UMCShare/Social/ReducedSina'
    pod 'UMCShare/UI'
    pod 'TABAnimated'
    
    # Pods for EasyFast
  end

end
