# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'EasyFast' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'ReactiveObjC'
  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'Masonry'
  pod 'IQKeyboardManager'
  pod 'SDWebImage'
  pod 'MBProgressHUD'
  pod 'DateTools'
  pod 'YYKit'
  pod 'LYEmptyView'
  pod 'CYLTabBarController'
  pod 'QMUIKit/QMUIComponents/QMUIButton'
  pod 'QMUIKit/QMUIComponents/QMUITableView'
  # Pods for EasyFast

end
